site_name: Call of Duty Black Ops III Mini Wiki

site_url: https://autumnnippert.github.io/cod_miniwiki/
theme:
  name: material
  # logo: media/logo.png

  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      primary: orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: orange
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

  features:
    - navigation.expand
    - navigation.instant
    - navigation.path
    - navigation.indexes

    - toc.follow

    - search.suggest
    - search.highlight

  plugins:
      - search

# extra_css:
#   - stylesheets/extra.css
# extra_javascript:
#   - javascripts/extra.js

markdown_extensions:
    - attr_list

nav:
    - Home: 'index.md'
    - Super Guide:
      - Getting Started: 'super_guide/start.md'
      - Additional Support: 'super_guide/support.md'
      - Tutorials: 'super_guide/tutorials.md'
      - Radiant Black - Keyboard Shortcuts: 'super_guide/radiant.md'
    - Notifies: 'notifies.md'
    - Callbacks: 'callbacks.md'

repo_url: https://github.com/AutumnNippert/cod_miniwiki